

export const metadata = {
    title: 'Squid Digital Solutions | SOLICITAR ORÇAMENTO',
    description: 'Generated by Next.js',
  }

  export default function DashboardLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {
    return (
      <section>        
        {children}
      </section>
    )
  }