import Analise from '@/components/analise/page';

export const metadata = {
  title: 'Squid Digital Solutions | SERVIÇOS',
  description: 'Generated by Next.js',

}


export default function ServicesLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {
    return (
      <section>
        
        {children}
        {<Analise/>}
      </section>
    )
  }
