import Header from "@/components/header/page";
import Footer from "@/components/footer/page";
import Analise from '@/components/analise/page';

import './home.css';

export const metadata = {
  title: 'Squid Digital Solutions',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        {<Header/>}
        {children}
        {<Footer />}

      </body>
    </html>
  )
}
